modLoader="javafml"
loaderVersion="[43,)"
license="GNU Lesser General Public License v2.1 (LGPLv2.1)"

[[mods]]
modId="ghostutils"
version="${file.jarVersion}"
displayName="Ghost Utilities"
displayURL="https://www.curseforge.com/minecraft/mc-mods/ghostutilities"
logoFile="ghostutils_logo.png"
authors="Tictim"
description='''Client-sided useful overlays'''